name: music
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.1 <4.0.0"

dependencies:
    audio_video_progress_bar: ^2.0.3
    audioplayers: ^6.0.0
    file_picker: ^8.0.3
    flutter:
        sdk: flutter
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    marquee: ^2.2.3
    mime: ^1.0.5
    path_provider: ^2.1.3
    provider: ^6.1.2
    shared_preferences: ^2.2.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    isar_generator: ^3.1.0+1
    build_runner: ^2.4.11

flutter:
    uses-material-design: true

dependency_overrides:
    fading_edge_scrollview: ^4.1.1
